### ISSUE TITLE
How Load exists PirvateKey?

### ISSUE THREAD

**Issue by lamb-mei** [imachug/sslcrypto#14]
if Privatekey already exists
How to load a string(PEM) or file to ECCKey

**Comment by imachug** [comment]
sslcrypto uses `bytes` to store private keys, so just passing a key in raw format should work. See [this test file](https://github.com/imachug/sslcrypto/blob/c829d20599339f0f567dfae5f4dedd26311790c4/test/test_basic.py#L83) for example.

Alternatively, you can use WIF format like this:

```python
priv = curve.wif_to_private(b"5JpCC7mMHxZ8Lw9TwUymMzdcfWeLVi8r8Tyyz5ic6G12iqAXr6E")
curve.sign(data, priv, ...)
```

**Comment by imachug** [comment]
I assume your question is answered. Feel free to reopen this issue if you have more questions.
