### ISSUE TITLE
Licensing issue. Removal from Python Package Index

### ISSUE THREAD

**Issue by binarypunk** [imachug/sslcrypto#4]
Hello, 

This is a legal warning to stop this repository immediately because you copied from other peoples work and claiming it as yours under a different license. I request you to remove your package voluntary from the Python Package Index before I report this package for removal from https://pypi.org/.

If you interested I can present the original works you copied from most of your code.

**Comment by imachug** [comment]
> If you interested I can present the original works you copied from most of your code.

Yes, I am. I am sure that the only part you can find is related to `_ripemd.py` (almost everything) and `_jacobian.py` (about a half, I could implement it all myself but I'd write almost the same code). Both of these files contain license notices.

Is there anything else I missed?

**Comment by binarypunk** [comment]
Not only! You know it well. 

Let me quote for you a license: 
```
This software is made available under the terms of *either* of the licenses
found in LICENSE.APACHE or LICENSE.BSD. Contributions to cryptography are made
under the terms of *both* these licenses.

The code used in the OpenSSL locking callback and OS random engine is derived
from CPython, and is licensed under the terms of the PSF License Agreement.
```

**Comment by imachug** [comment]
Ok... now what code did I copy from `cryptography`?

**Comment by binarypunk** [comment]
Do I really need to include here all the code? You know it well. You made this compilation. 
You are not allowed to relicense it as MIT in any way!

**Comment by imachug** [comment]
> Do I really need to include here all the code?

Yeah, you do. You can't just say I compiled stuff from other projects without any proofs.

**Comment by binarypunk** [comment]
Yes, you did! `_ripemd.py` alone preventing you to put an MIT license on this compilation! That is a **proprietary** code! It doesn't grant you any right for relicensing!

**Comment by filips123** [comment]
> That is a proprietary code! 

No it is not!

**Comment by imachug** [comment]
This is a BSD 2-clause license. Let me quote the only related condition:

> 1. Redistributions of source code must retain the above copyright
>    notice, this list of conditions and the following disclaimer.

Did I retain the copyright notice? Yes, I did -- the comment. Did I retain the list of conditions? Yes, I did. Did I retain the disclaimer? Yes, I did -- go read the comment.

Relicensing is allowed by default. It doesn't have to be granted anyhow.

**Comment by binarypunk** [comment]
All rights reserved!!!

**Comment by binarypunk** [comment]
Not allowed! If the license not saying you are allowed to relicense than you are not allowed! Is that simple!

**Comment by filips123** [comment]
F*cking every license include "All rights reserved"!!! The important part are conditions after it.

**Comment by binarypunk** [comment]
Show me a GPL license which has `All right reserved` in it! You are a joke!

**Comment by imachug** [comment]
> If the license not saying you are allowed to relicense than you are not allowed

Eh... 

> # Redistribution and use in source and binary forms, with or without
> # modification, are permitted provided that the following conditions
> # are met:

I followed all the conditions so I can use it in source. What don't you understand?

**Comment by binarypunk** [comment]
It is NOT granting you rights to OVERRIDE his copyrights! He specifically stated: ALL RIGHTS RESERVED and I see no permission for relicensing!

**Comment by imachug** [comment]
Ok, I can add 

> Additionally, the following licenses must be preserved:
>
> - ripemd implementation is licensed under BSD-3 by Markus Friedl, see `_ripemd.py`;
> - jacobian curve implementation is dual-licensed under MIT or public domain license, see `_jacobian.py`.

...to the license text if you want me to. Is that ok?

**Comment by binarypunk** [comment]
It would be the minimum!!!! But still you CAN'T relicense anything to MIT which is not your work! Only your original work can be licensed under MIT! Try to separate them and use **`import`** when you need!!!!

**Comment by imachug** [comment]
Eh... I *do* import when I need.

**Comment by imachug** [comment]
And they are already separated.

**Comment by binarypunk** [comment]
Your work and only your work must be in a separate file. You can't use any code from others and claim it is licensed under MIT. Yes I see when you use import... But you mixed up the code and this is not allowed. The license file should include all copyright notices and the files which licensed under them! You can't claim MIT license under anything what you did not wrote! 



> And they are already separated.
Show me just one file which contains only you code! Go ahead.

**Comment by imachug** [comment]
> But you mixed up the code

What code did I mix?

**Comment by imachug** [comment]
> Show me just one file which contains only you code! Go ahead.

Oh? Sure: `sslcrypto/_ecc.py`. There's also `sslcrypto/openssl.py`, `sslcrypto/fallback/ecc.py` and many others.

**Comment by binarypunk** [comment]
This is not your code. You have changed but is not your!

**Comment by imachug** [comment]
Why is it not mine? What did I copy *now*?

**Comment by binarypunk** [comment]
I show you just a few. Let's say from `openssl.py `

Most code is rewritten from [cryptography](https://github.com/pyca/cryptography/blob/master/LICENSE). 

Everything which is not originates from you are preventing you to put any copyright on it specially relicensing it! Did you "invented" all this alone in a few days?

**Comment by imachug** [comment]
BTW, check [this](https://github.com/spesmilo/electrum/commit/305843999eabdb4276109e3dc6b70bf21dbbc29a). Even electrum guys are licensing their software under MIT *and* using that implementation. Can you go sue them too please?

**Comment by imachug** [comment]
> Did you "invented" all this alone in a few days?

Uh... how do you define "invented"? If you're referring to ECC, I didn't but literally no one else did. If you're referring to the actual code... Well yes.

**Comment by binarypunk** [comment]
No is not your code. You also said it! It includes BSD licensed code and also **proprietary** not to mention [cryptography](https://github.com/pyca/cryptography/blob/master/LICENSE). You must license it under GPLv3 and add a LINKING EXCEPTION to these licenses in your LICENSE file! Otherwise you can't distribute it at all.

**Comment by krixano** [comment]
@binarypunk Shut the fuck up, because you are an idiot.

> "All rights reserved" is a copyright formality indicating that the copyright holder reserves, or holds for its own use, all the rights provided by copyright law.

What does this mean? This means that the person reserved COPYRIGHT. It means THEY CAN ALLOW PEOPLE TO USE THE CODE BECAUSE THEY HOLD COPYRIGHT.

> By having the all rights reserved notice, and then a license, you're affirming it's your work and your rights, but you allow people to do these specific things with it.

> The "All rights reserved" phrasing is a way to claim copyright, not to say any/no permissions are granted. This follows from the Buenos Aires copyright convention, which had some signatories not in the Berne Convention (notably Nigaragua and the US), and required for protection that "the reservation of the property right appeared in the work". AFAIK there are no remaining countries that have ratified the Buenos Aires convention but not Berne.

**Comment by binarypunk** [comment]
He don't hold copyright over this compilation! Period. And you little fuck get lost before I go to Germany and smash your little face.

**Comment by imachug** [comment]
I am distributing this project under the following license:

- MIT for the whole project;
- Users must *also* follow MIT license of the jacobian curve implementation;
- Users must *also* follow BSD 2-clause license of the ripemd implementation.

**Comment by imachug** [comment]
> Period

Not period. I guess I'm too dumb to understand how your brain works so I'd better listen to your explanations once again.

**Comment by binarypunk** [comment]
> By having the all rights reserved notice, and then a license, you're affirming it's your work and your rights, but you allow people to do these specific things with it.

Yah! You allowed to buy a book **and read it in private!!** You can't reprint it and relicense it as your!

**Comment by imachug** [comment]
See, this project includes:

- my own code;
- others' code.

This project can be distributed under MIT *and* others' licenses (it's *and*, not *or* as in dual-licensing). What's the problem?

**Comment by krixano** [comment]
@binarypunk What you are literally saying is that every BSD-licensed project is proprietary, did you know that?

ALL bsd licenses have "All rights reserved"... now are we going to say that all BSD projects are proprietary?

Again, 1.) The phrase has no legal meaning - it's obsolete and is only used for convension.
2.) "All Rights Reserved" allows the copyright holder to retain the right to give people permission to use the code - which is precisely what the BSD license does.

**Comment by binarypunk** [comment]
You see the problem is that `_ripemd.py` doesn't state any license. Only states that ALL RIGHT RESERVED! Some conditions and a disclaimer. Meaning it is **proprietary**. You can't put any license on "others code"! That is why I highly recommend GPLv3. As I said most of the code is NOT your even in the files your claim that you wrote. I can show you pastebin, GitHub and other places from where you copied.

**Comment by filips123** [comment]
@binarypunk What is then [this](https://github.com/imachug/sslcrypto/blob/master/sslcrypto/_ripemd.py#L3-L21)?

**Comment by binarypunk** [comment]
> @binarypunk What is then [this](https://github.com/imachug/sslcrypto/blob/master/sslcrypto/_ripemd.py#L3-L21)?

We know this @filips123... But if you read it just now than show me where it says the license or permission to relicense it.

**Comment by filips123** [comment]
This is called [BSD-2 Clause](https://opensource.org/licenses/BSD-2-Clause).

**Comment by krixano** [comment]
You don't need to state the license name, it's idiotic to think that. The permissions were granted, that's literally all that matters.

**Comment by binarypunk** [comment]
Not exactly @krixano he did not granted permission to copy and include his code in a compilation which is than relicensed as MIT. He said use, modify and distribute. **Not to relicense!**

**Comment by binarypunk** [comment]
@imachug I think you need GPLv3!

**Comment by filips123** [comment]
![slika](https://user-images.githubusercontent.com/16626308/69011268-21b5cc80-0969-11ea-9dd3-ddb41b8f64ea.png)

> 2-clause license ("Simplified BSD License" or "FreeBSD License")
> Linking from code with a different license: Yes

**Comment by krixano** [comment]
Yeah, I get what you're saying... it's dumb. You're a disgusting type of person that tries to take down lots of projects for technicalities.

**Comment by krixano** [comment]
Exactly @filips123 Even the BSD creators, who *put the "all rights reserved" line in there when they created the license* thinks that you can sublicense. lol

**Comment by binarypunk** [comment]
No @krixano 
I'm just looking out for my and others interest. You however misleading everyone, lying to over a 100 contributors in ZeroNet, and hiding facts. Who is the dumb and shameful? You my friend. I want to help right now @imachug too and I highly recommend to use GPLv3! That is very very permissive! @krixano is a retard. don't listen this this guy @imachug ! Look what he tried to do with ZeroNet. ZeroNet should be free and open for everyone that is FREE SOFTWARE! And your compilation (because it is) would be useful for many later on! Not only for ZeroNet but for other people around the world! BSD MIT and all other shit are built for US law not for International use! Think about @imachug !

**Comment by filips123** [comment]
> GPLv3 [...] That is very very permissive!

That tells how much you know about licenses...

**Comment by binarypunk** [comment]
**Permissive and international!** 

(hope for you little brain this 3 words are enough and not overloading it)

**Comment by imachug** [comment]
> don't listen this this guy

lmao, I've known krixano waaaay longer before you came here

**Comment by binarypunk** [comment]
Doesn't matter @imachug he is a retard. You deserve better people around you who actually do know the law. Not some retarded German pokemon player.

**Comment by imachug** [comment]
You know, GPL is *less* permissive than MIT and/or public domain. I'm thus keeping MIT as one of the most permissive licenses.

**Comment by binarypunk** [comment]
**Who protects you from corporations who will still your code?** 

**How you make your code compatible all around the world?** as I said MIT and other BSD Apache etc are built for US law!

**Comment by filips123** [comment]
?

**Comment by binarypunk** [comment]
GPLv3 is the only license which will protecting you internationally and preventing corporations to steal your code!

**Comment by filips123** [comment]
Yes. That's why the most used open-source license is MIT...
Also, what if @imachug don't care if "corporations steal his code"? Why should he license it as GPLv3?

**Comment by binarypunk** [comment]
@filips123 you don't understand do you? I can steal any program which is licensed under MIT if I really want to because MIT is a U.S license! It can't be enforced for example in Russia!

**Comment by filips123** [comment]
> because MIT is a U.S license!

And GPL is not?

**Comment by binarypunk** [comment]
> > because MIT is a U.S license!
> 
> And GPL is not?

GPLv3 using terminology which makes it possible to enforce in any country! Not only in the U.S.A! That is it's real power! But is hard for you to understand I can imagine. Please do your research!

**Comment by filips123** [comment]
?

**Comment by binarypunk** [comment]
GPLv3 can be enforced in all countries of the world! Also it is very bad for corporations who want to steal your code because they can't! GPLv3 is built by many-many people with international law in mind and also taken steps to make it compatible with other licenses like BSD Apache etc... It is a very big deal and I'm sure even @krixano can get it now why matters!

**Comment by imachug** [comment]
> preventing corporations (or anyone else) to steal your code!

I allow corporations to use my code, that's one of the reasons of making this library.

**Comment by filips123** [comment]
Explain why MIT can't be? And why it is then the most popular open-source license?

**Comment by krixano** [comment]
@imachug If you care about the patent-protection crap, there's the special-purpose BSD+Patent license: https://opensource.org/licenses/BSDplusPatent

**Comment by binarypunk** [comment]
@krixano is not only the "patent crap" it is also terminology and compatibility! GPLv3 is international covering the entire world!

**Comment by filips123** [comment]
Again:

> Explain why MIT can't be? And why it is then the most popular open-source license?

**Comment by binarypunk** [comment]
> Forcing everyone who uses GPLv3 licensed library to also license it under GPLv3.

:rofl: Where you read that?

**Comment by filips123** [comment]
> GPLv3 is international covering the entire world!

🤣 Where you read that?

**Comment by imachug** [comment]
LMAO. Do you know how licensing works?

**Comment by binarypunk** [comment]
> > GPLv3 is international covering the entire world!
> 
> rofl Where you read that?

The whole license! :roll_eyes:

**Comment by filips123** [comment]
Explain why MIT isn't covering the entire world?

**Comment by binarypunk** [comment]
Sure @filips123 if you really want I can explain, I just don't get it why you don't go and read?

**Comment by filips123** [comment]
Yes, explain please.

**Comment by filips123** [comment]
> 
> 
> > Forcing everyone who uses GPLv3 licensed library to also license it under GPLv3.
> 
> 🤣 Where you read that?

Read this:

> MIT licensed software can be integrated into GPL software, but not the other way around.

**Comment by binarypunk** [comment]
> MIT licensed software can be integrated into GPL software, but not the other way around.

That is correct! What is the problem?

**Comment by filips123** [comment]
I will explain when you explain why MIT isn't global license.

**Comment by binarypunk** [comment]
Shortly, because it is unenforcable outside of United States! This is due to terminology and copyright law!

**Comment by filips123** [comment]
Explain and prove! And explain why then GPL is forcable outside of United States.

**Comment by binarypunk** [comment]
Not any GPL! **Only GPLv3!**

**Comment by filips123** [comment]
Explain more!

**Comment by binarypunk** [comment]
Sure! I'm on it @filips123 choosing the right words for you to make it understandable.

**Comment by binarypunk** [comment]
Actually, **Debian legal team** had a presentation about this.

**Comment by filips123** [comment]
![slika](https://user-images.githubusercontent.com/16626308/69011935-58431580-0970-11ea-9a86-9491157c2bea.png)

**Comment by binarypunk** [comment]
omg... please do not requote yourself. I have seen it!

**Comment by binarypunk** [comment]
@filips123 until I write for you please read these: 

- https://worthhiding.com/2018/01/18/licenses-loopholes-and-litigation-a-comprehensive-survey-of-software-case-law-and-open-source-licensing-in-the-united-states/
- https://www.oreilly.com/library/view/understanding-open-source/0596005814/ch06.html

**Comment by krixano** [comment]
So, you say MIT is *only* enforceable in the US, and then give us an article that says that MIT *might* not be enforceable in the US, lol

> While shrinkwrap licenses have been declared enforceable, the only open source licenses that have been held up in court are the Artistic License and GPLv3. The MIT License, GPLv2, and Apache 2.0 have not—no legal precedent regarding their enforceability exists—and therefore there exists a risk that the terms are without weight.

**Comment by binarypunk** [comment]
Just a quick note, MIT also doesn't require to include the copyright notice in derivative works. While it says preserved there is nothing can stop someone to release a closed sourced program etc. MIT is permissive license **not copyleft**! **Failing to comply with MIT doesn't terminate the license** like GPLv3! This is a real danger by its own.

**Comment by filips123** [comment]
Yes it does:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

**Comment by filips123** [comment]
> MIT is permissive license not copyleft! 

Yes, that why @imachug chosen it.

**Comment by krixano** [comment]
> MIT is permissive license not copyleft! Failing to comply with MIT doesn't terminate the license like GPLv3! This is a real danger by its own.

It's the author's decision on whether they want MIT or not.

**Comment by krixano** [comment]
It's *also* the author's decision on whether they care about the license working in all countries or not.

**Comment by binarypunk** [comment]
Still, it is unenforcable outside of USA. I wonder how you planning to enforce it in Russia or China. @imachug lives in Russia and he is 23 years old. I can imagine now he makes a mistake and some corporation picks up his work and will not comply with MIT because they are not required under the law of that country. When he is 40 years old he regrets his decision because of you..Think about.

**Comment by krixano** [comment]
@binarypunk Why do you care so much. This isn't your code. You have *no* say. **Just because you care about this crap, doesn't mean other people have to.**

**Comment by binarypunk** [comment]
Because I know he is a good person and I want to help him just as I want to help ZeroNet. I doing my best to make sure everyone understands how serious is the licensing issue.

**Comment by krixano** [comment]
You're so full of it.

**Comment by binarypunk** [comment]
> Just because you care about this crap, doesn't mean other people have to. 

You are full of :hankey: I'm sorry but this is true. Do you even read my comments? :roll_eyes:

**Comment by imachug** [comment]
I don't want the license to be enforced as long as I am not affected by it in any way. I'd use Public Domain license but AFAIK it works in fewer countries than MIT. If anyone asks me to dual-license this software under whatever license they want, I'd accept that in most cases.

**Comment by binarypunk** [comment]
Again, back to the opening. This is not your code. You are not allowed at all to relicense BSD or anything else like Apache to MIT! Do what you want but I guarantee you will regret it!

**Comment by krixano** [comment]
>  You are not allowed at all to relicense BSD or anything else like Apache to MIT! Do what you want but I guarantee you will regret it!

yes he is, not shut up.

**Comment by binarypunk** [comment]
Saying who? You? Go make some music Christian...

**Comment by krixano** [comment]
You just stated that the only license that is enforceable is GPL and the Artistic one... therefore BSD is not technically enforceable in the US, right?

Stop contradicting yourself, lol. You look like an idiot.

**Comment by binarypunk** [comment]
I know all of you I did my research and the only valuable person here is @imachug He is extremely intelligent!

**Comment by krixano** [comment]
LOL, you "know" me? Just stop, I'm laughing too much.

**Comment by binarypunk** [comment]
Yes I know you, I know about your exclusion in school, hobbies your past everything really...

**Comment by krixano** [comment]
> exclusion in school

Care to elaborate?

**Comment by binarypunk** [comment]
You know for what I referring... Don't need to elaborate.. This is closed by @imachug you can write me email to mammamia@zeronet.website :rofl:

**Comment by krixano** [comment]
The fact is you only what is online about me, what I explicitly put only

Btw, "exclusion in school" means nothing in English... do you mean I got "expelled"? I have no idea what "exclusion in school" means.

**Comment by binarypunk** [comment]
One more thing. I give to @imachug both zeronet.website and zeronet.host if he needs it for free! He well deserve them.

**Comment by binarypunk** [comment]
@imachug do you use imachug@gmail.com? I send the domains there if you want.

**Comment by krixano** [comment]
If you mean I got **expelled** from school, I didn't... soooo.....

**Comment by imachug** [comment]
Let me jump in and mention that you know literally nothing about me and the information you provided is plain wrong. You don't know me and I don't know you. This is the Internet.

I don't care about licenses as long as I am not affected in any way.

**Comment by binarypunk** [comment]
I do know you. I also have worked for FSB. ;)

**Comment by krixano** [comment]
No idea what FSB is, lol

**Comment by binarypunk** [comment]
Better @krixano ! 
Listen to me: https://www.youtube.com/watch?v=yvcj2R6wKe0 :+1:

**Comment by krixano** [comment]
If you can't explain what "exclusion" is then I think we all know that that means you don't really know me.

**Comment by binarypunk** [comment]
I like you too just stop arguing :laughing:

**Comment by krixano** [comment]
I mean, you've previously called me Hungarian, and German, and Nazi, and all of this other crap... so I think that kinda proves my point.

**Comment by binarypunk** [comment]
:angry Are you? I don't think so anymore. Thanks to god you are not a Hungarian fascist...

**Comment by binarypunk** [comment]
:wave:

**Comment by krixano** [comment]
Ah, right. **Now** you go back on everything you've said previously, lol

**Comment by binarypunk** [comment]
I'm sorry for saying all those things about you and to you! :cry: :smiling_imp:

**Comment by krixano** [comment]
Oooh, look at me! I can read a website and search the name "krixano" on Google to get to a person's YouTube channel where they post their music and where they explicitly put their name! I must Know this person!

lmfao

**Comment by binarypunk** [comment]
:rofl:

**Comment by binarypunk** [comment]
See ya @krixano !

**Comment by krixano** [comment]
FYI, I was never expelled from any school (still don't know what "exclusion from school" means). I had a 4.3/5 GPA in High School and I'm still in College.

**Comment by binarypunk** [comment]
# :+1:

**Comment by binarypunk** [comment]
What you study? Computer Science?

**Comment by krixano** [comment]
Not exactly hard to figure out, is it? lmfao

**Comment by binarypunk** [comment]
No is not hard! :+1: I guess

**Comment by binarypunk** [comment]
I need to work on ZeroNet :rofl: We talk later. Maybe on IRC but I don't see you there a lot, @filips123 and @imachug are there usually and a few bot also :rofl:

**Comment by krixano** [comment]
Right.. you can read a website, lol

**Comment by binarypunk** [comment]
:astonished: :+1: **Хорошо́**

**Comment by krixano** [comment]
@binarypunk  Btw, don't act like you know me because you can read some information on the Web (and perhaps Gopher) that talks about my life.

You only know what I let people know online. Knowing a summary of a person's life is not the same as knowing someone.

**Comment by binarypunk** [comment]
That's right @krixano

**Comment by imachug** [comment]
@binarypunk That just proves you don't know Russian... at least you don't know it well.

**Comment by binarypunk** [comment]
@imachug I was obligated to learn (write and speak) Russian! I forgotten a lot over the time.

**Comment by imachug** [comment]
I mean, it's kinda difficult to forget *not* to put accents in Russian.

**Comment by binarypunk** [comment]
Trust me in 17 years I did forget a lot specially Russian

**Comment by krixano** [comment]
> Soon or later you will know me too. My real name etc.

You haven't proved that you know *one* thing about me that I haven't put online, so sorry if I don't believe you

**Comment by binarypunk** [comment]
That is true @krixano I only know what you share and what others share about you.

**Comment by binarypunk** [comment]
I'm over 30 @imachug

**Comment by imachug** [comment]
Sure, that says a lot about me.

**Comment by krixano** [comment]
> and what others share about you.

And what do others share about me?

**Comment by binarypunk** [comment]
In time @imachug in time. Still I'm interested in you use case of ZeroNet. For that matter I don't see so many people talking about how they use ZeroNet. Any valuable use case? Except Daily Stormer and :hankey: ...

**Comment by binarypunk** [comment]
@krixano You good with cards :rofl:

**Comment by binarypunk** [comment]
@imachug make this repo a template and than after cloning it you can delete it so the issue and pr will not show up...

**Comment by imachug** [comment]
@binarypunk Just to let you create another issue? Sorry but no. BTW, closing this issue isn't worse.

**Comment by krixano** [comment]
@binarypunk So far you've told me one false information, which is that I was "excluded" from school. Now you are telling me people talk about how good I am at "cards"? Hm.... fishy

**Comment by krixano** [comment]
> Not some retarded German pokemon player.

@binarypunk You think I'm a German Pokemon player? LMFAO.

**Comment by krixano** [comment]
So, first I was Russian, then Hungarian, then a Nazi, and now a German Pokemon player! And apparently I was expelled/excluded from school for having a 4.3 GPA!

I think you are searching my name online and assuming that I'm connected with this other "Christian Seibold" just because I have the same name? Or perhaps you are just lying straight through your teeth.

**Comment by krixano** [comment]
@binarypunk I'm guessing you think I'm this person?

https://magic.wizards.com/en/events/coverage/gpwar18/sf-dq-statement-2018-11-25

You do know multiple people can have the same name, right?

**Comment by binarypunk** [comment]
:astonished: :ear:

**Comment by krixano** [comment]
It's not.

**Comment by binarypunk** [comment]
You are not a wizard? :sob:

**Comment by binarypunk** [comment]
https://www.youtube.com/watch?v=J2A8D1dwwEY This is you for sure! :+1:

**Comment by krixano** [comment]
Never heard of that game in my life.
If you search farther in Google, you will see that there are more people who have the exact same name as me.

**Comment by krixano** [comment]
> https://www.youtube.com/watch?v=J2A8D1dwwEY This is you for sure! +1

*That* is me... but the other person from the game is not.

**Comment by binarypunk** [comment]
Try [EasyScreenCast](https://github.com/EasyScreenCast/EasyScreenCast) I use it on Kali.

**Comment by binarypunk** [comment]
:rofl: @imachug Look at this! https://github.com/EasyScreenCast/EasyScreenCast/blob/master/COPYING.md `COPYING`

**Comment by filips123** [comment]
They are just using `COPYING`. This is same as just using `LICENSE`.

**Comment by imachug** [comment]
It's COPYNG without .md btw.

**Comment by binarypunk** [comment]
Ohh, is just GPLv3 not +

**Comment by filips123** [comment]
Yes, but GPLv3+ notice could be included in README...

**Comment by binarypunk** [comment]
> Yes, but GPLv3+ notice could be included in README...

This is where we disagree, it need to be in `LICENSE` you know why? Because of the **linking exceptions** also need to be there! COPYING should contain the full license like this one!

**Comment by filips123** [comment]
What if linking exceptions are also in README?

**Comment by binarypunk** [comment]
:rofl: Never give up even if I'm right?

**Comment by filips123** [comment]
Yes, which also appears to be true for you...

**Comment by filips123** [comment]
You still haven't explained why linking exceptions and "or later" notice can't be placed in README?

**Comment by binarypunk** [comment]
You just earned that :heart: :rofl:

**Comment by binarypunk** [comment]
@filips123 Check this out: 

- https://github.com/GNOME/gimp/blob/mainline/LICENSE
- https://github.com/GNOME/gimp/blob/mainline/COPYING
- https://github.com/GNOME/gimp/blob/mainline/INSTALL.in

GIMP enough modern for you?
